### ISSUE TITLE
Enable group synchronization

### ISSUE THREAD

**Issue by jmprieur** [SonarQubeCommunity/sonar-auth-aad#1]
SonarQube 5.5 will enable group synchronization.
This issue is to track the work on updating the SonarQube AAD provider to enable the group synchronization.

**Comment by wpschaub** [comment]
Closed by mistake.

**Comment by hkamel** [comment]
This is now handled in the new **release 1.1 Release Candidate 1 ** [https://github.com/SonarQubeCommunity/sonar-auth-aad/releases/tag/1.1-RC1]
