### ISSUE TITLE
Plugin Not Listed in SonarQube Update Center

### ISSUE THREAD

**Issue by mack0196** [SonarQubeCommunity/sonar-auth-aad#11]
I tested with new installs of sonarqube-6.0 and sonarqube-6.1 and Azure Active Directory (AAD) Authentication Plug-in for SonarQube is not listed in the Update Center. 
![image](https://cloud.githubusercontent.com/assets/6463105/20269525/0fa5c90a-aa49-11e6-9091-8ecd6960ee3c.png)

**Comment by mack0196** [comment]
I see the plug in is set to incompatible with SonarQube 6.0 and 6.1 @ http://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix.

Last week it was an option in both 6.0 and 6.1. I installed it and it worked for the authentication scenario I tested it with. 

What needs to be done to get the AAD Authentication Plugin compatible with 6.0 and 6.1?

**Comment by mack0196** [comment]
https://groups.google.com/forum/#!topic/sonarqube/DHEyyWRKrIo
Long story short, it looks like this plug in is not considered compatible by the SonarQube team.

Is there a plan to bring AAD Authentication plugin into compatibility with SonarQube 6?

**Comment by hkamel** [comment]
@mack0196 Thank you for raising this issue, I'll investigate more the compatibility and get back to you.

**Comment by baywet** [comment]
I had to install a 6.1 SQ instance on linux today with the AAD plugin. Manually installed the plugin, works like a charm. Only thing I noticed, redirection after login on AAD is slow.

**Comment by mack0196** [comment]
Where can I find instructions on how to manually install AAD plugin?

**Comment by baywet** [comment]
I don't know whether you're running SQ on linux or windows. On linux you just have to download the plugin from the release section on github here. Then copy it to /opt/sonarqube/extensions/plugins and reboot the server.

**Comment by Jazaret** [comment]
Has there been any update on this? I'm planning on updating Sonar to v6 but I'm waiting on AAD.  Thanks!

**Comment by hkamel** [comment]
Hello team,

As per this thread https://groups.google.com/forum/#!topic/sonarqube/DHEyyWRKrIo the plug-in was marked as incompitable by mistake and it should be fixed now. the Plugins page has been updated http://docs.sonarqube.org/display/PLUG/Plugin+Version+Matrix

**Comment by Jazaret** [comment]
Excellent thank you
