### ISSUE TITLE
You're not authorized to access this page. Please contact the administrator.

### ISSUE THREAD

**Issue by MrBeanzy** [SonarQubeCommunity/sonar-auth-aad#12]
After setting up Sonar AAD when clicking the "Login With Azure AD" button im redirected to an unauthorized page that says "You're not authorized to access this page. Please contact the administrator." Im using the 1.1-RC1 build

**Comment by hkamel** [comment]
Hello @MrBeanzy which version of SonarQube are you using? could you please also share the log.

Just make sure you have SonarQube Server URL set to HTTPs in SonarQube settings

**Comment by MrBeanzy** [comment]
@hkamel Thanks for the tip, I had mistakenly put HTTP not HTTPS. I now get this error.

The page you were looking for doesn't exist.
You may have mistyped the address or the page may have moved.

This could be down to the IIS Reverse Proxy so ill have a bit of a play and report back.

**Comment by hkamel** [comment]
@MrBeanzy glad we identified an issue, please follow the following blog post for how to correctly configure IIS as a reversed proxy https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/06/04/running-sonarqube-behind-an-iis-reversed-proxy/

**Comment by IvanBoyko** [comment]
@hkamel 
I've got exactly the same error in SonarQube web interface, but the root cause was different:

> 2017.03.03 09:54:46 ERROR web[AVqTlh3aAupP6eiOAAAN][o.a.a.a.AadIdentityProvider] Exception:org.sonar.api.server.authentication.UnauthorizedException: You can't sign up because email '\<my-email-address\>' is already used by an existing user. This means that you probably already registered with another account.
> 2017.03.03 09:54:46 ERROR web[AVqTlh3aAupP6eiOAAAN][o.s.s.a.AuthenticationError] Fail to callback authentication with 'aad'
> java.lang.IllegalStateException: Fail to authenticate the user:org.sonar.api.server.authentication.UnauthorizedException: You can't sign up because email '\<my-email-address\>' is already used by an existing user. This means that you probably already registered with another account.
>         at org.almrangers.auth.aad.AadIdentityProvider.callback(AadIdentityProvider.java:132)
> ...

As I was the one who created this SonarQube instance, I've obviously created local user with my email address first, before trying Azure AD plugin.
Potentially this kind of errors could be shown to user (i.e. in the web interface of SQ)?

Thanks for the idea to check the logs.
As I run SonarQube as a Docker container, and it sends output to container console, the easiest way to see logs is to run `docker logs -f sonarqube` - might help someone.

**Comment by IbrahimUmar** [comment]
https://developercommunity.visualstudio.com/content/problem/896216/sonarqube-integration-with-saml.html

**Comment by kubragogebakan** [comment]
Hello,

Do you have any updates related issue? I saw the error after AAD - SonarQube integration in web log file.
"Exception:org.sonar.server.authentication.exception.EmailAlreadyExistsRedirectionException" 

SonarQube version is: 8.2
MS SQL Server version is: 12.00.2000
PS: We deploy the SQ as container on Azure Kubernetes Service.

Here is the full log getting from web log file.
2020.04.30 09:59:15 INFO  web[][c.m.a.a.AuthenticationAuthority] [Correlation ID: 765f023c-2ab4-4ad6-ae17-3ffb7f3defb7] Instance discovery was successful
2020.04.30 09:59:15 DEBUG web[][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@492cfef213 pairs: {POST /16297908-3fdb-493e-8c51-7b060e600229/oauth2/token HTTP/1.1: null}{return-client-request-id: true}{client-request-id: 765f023c-2ab4-4ad6-ae17-3ffb7f3defb7}{x-client-CPU: amd64}{x-client-VER: 1.6.2}{x-client-SKU: java}{x-client-OS: Linux}{Content-Type: application/x-www-form-urlencoded; charset=UTF-8}{User-Agent: SonarQube 8.2.0.32929 # 67E6CD34-AXDy9ZlwhWD_lplUDmBO Java/11.0.6}{Host: login.microsoftonline.com}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}{Content-Length: 1089}
2020.04.30 09:59:16 DEBUG web[][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@19ce687f17 pairs: {null: HTTP/1.1 200 OK}{Cache-Control: no-cache, no-store}{Pragma: no-cache}{Content-Type: application/json; charset=utf-8}{Expires: -1}{Strict-Transport-Security: max-age=31536000; includeSubDomains}{X-Content-Type-Options: nosniff}{client-request-id: 765f023c-2ab4-4ad6-ae17-3ffb7f3defb7}{x-ms-request-id: c573ce36-ca97-4abd-b539-f18c77cb0f00}{x-ms-ests-server: 2.1.10433.14 - EST ProdSlices}{x-ms-clitelem: 1,0,0,,}{P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"}{Set-Cookie: fpc=Aj5KIsCZUl9CuwmlJmq3BCotowdQAQAAAHOYPNYOAAAA; expires=Sat, 30-May-2020 09:59:16 GMT; path=/; secure; HttpOnly; SameSite=None}{Set-Cookie: x-ms-gateway-slice=prod; path=/; SameSite=None; secure; HttpOnly}{Set-Cookie: stsservicecookie=ests; path=/; SameSite=None; secure; HttpOnly}{Date: Thu, 30 Apr 2020 09:59:15 GMT}{Content-Length: 4238}
2020.04.30 09:59:16 DEBUG web[][c.m.a.a.AuthenticationContext] [Correlation ID: 765f023c-2ab4-4ad6-ae17-3ffb7f3defb7] Access Token and Refresh Token were returned
2020.04.30 09:59:16 ERROR web[AXHKXSXoJ+mWDwTFAADk][o.a.a.a.AadIdentityProvider] Exception:org.sonar.server.authentication.exception.EmailAlreadyExistsRedirectionException
2020.04.30 09:59:16 DEBUG web[AXHKXSXoJ+mWDwTFAADk][auth.event] login failure [cause|Plugin did not call authenticate][method|OAUTH2][provider|EXTERNAL|Microsoft][IP|192.168.0.39|192.168.0.35][login|]
2020.04.30 09:59:16 DEBUG web[AXHKXSXoJ+mWDwTFAADm][auth.event] login failure [cause|User must be authenticated][method|BASIC][provider|LOCAL|local][IP|192.168.0.39|192.168.0.35][login|]
2020.04.30 09:59:47 INFO  web[AXHKXSXoJ+mWDwTFAAD1][o.s.u.c.UpdateCenter] The plugin 'scmgit' version : 1.11.1.2008 has not been found on the update center.
2020.04.30 09:59:52 DEBUG web[AXHKXSXoJ+mWDwTFAAD2][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@7f69f62f5 pairs: {GET /systemInfo HTTP/1.1: null}{User-Agent: SonarQube 8.2.0.32929 # 67E6CD34-AXDy9ZlwhWD_lplUDmBO Java/11.0.6}{Host: 127.0.0.1:39211}{Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2}{Connection: keep-alive}
2020.04.30 09:59:52 DEBUG web[AXHKXSXoJ+mWDwTFAAD2][s.n.w.p.h.HttpURLConnection] sun.net.www.MessageHeader@30e9acdc5 pairs: {null: HTTP/1.1 200 OK}{Content-Type: application/x-protobuf}{Date: Thu, 30 Apr 2020 09:59:52 GMT}{Connection: keep-alive}{Content-Length: 9377}

**Comment by ChapChap** [comment]
Hi,

I am facing the same issue after DB migration and plugin update :
- I upgraded sonarqube from 7.9.1 to 8.9.0 and upgraded sonar-auth-aad from 1.2.0-RC1 to 1.2.0
- Everything was OK
- I dumped/restored the data to another environment (from postgres 10 to postgres 11)
- I am able to log but a colleague isn't able to.
I get the same error as shown above by @kubragogebakan 

I am planning to revert the plugin upgrade but idk what to do next, how to fix this ?
