### ISSUE TITLE
Support Sonarqube 6.x versions

### ISSUE THREAD

**Issue by andreamaruccia** [SonarQubeCommunity/sonar-auth-aad#13]
Tried to install this plugin on sonarqube 6.3.1 but with no success. 

I can see the plugin in the configuration settings, configured the plugin and azure application.
But I cannot seem to login (redirects to login page all the time)

**Comment by hkamel** [comment]
@andreamaruccia could you please check SonarQube log files (sonar.log) and share the log information

**Comment by andreamaruccia** [comment]
Tried with sonar 6.4 can't see anything special in the sonar.log file:

2017.06.08 14:11:41 INFO  app[][o.s.a.SchedulerImpl] Stopping SonarQube
2017.06.08 14:11:42 INFO  app[][o.s.a.SchedulerImpl] Process [ce] is stopped
2017.06.08 14:11:45 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.06.08 14:11:45 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2017.06.08 14:11:45 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
--> Wrapper Started as Service
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2017.06.08 14:11:46 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory C:\sonarqube-6.4\temp
2017.06.08 14:11:46 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[es]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-6.4\temp -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer C:\sonarqube-6.4\temp\sq-process4363502427220740184properties
2017.06.08 14:11:55 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2017.06.08 14:11:55 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[web]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-6.4\temp -cp ./lib/common/*;./lib/server/*;C:\sonarqube-6.4\lib\jdbc\mysql\mysql-connector-java-5.1.42.jar org.sonar.server.app.WebServer C:\sonarqube-6.4\temp\sq-process1589471312320119577properties
2017.06.08 14:12:25 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.06.08 14:12:25 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[ce]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-6.4\temp -cp ./lib/common/*;./lib/server/*;./lib/ce/*;C:\sonarqube-6.4\lib\jdbc\mysql\mysql-connector-java-5.1.42.jar org.sonar.ce.app.CeServer C:\sonarqube-6.4\temp\sq-process3417274957198354518properties
2017.06.08 14:12:31 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2017.06.08 14:12:31 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up
2017.06.08 14:14:30 INFO  app[][o.s.a.SchedulerImpl] Stopping SonarQube
2017.06.08 14:14:31 INFO  app[][o.s.a.SchedulerImpl] Process [ce] is stopped
2017.06.08 14:14:34 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.06.08 14:14:35 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2017.06.08 14:14:35 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
<-- Wrapper Stopped
--> Wrapper Started as Service
Launching a JVM...
Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
  Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.

2017.06.08 14:16:48 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory C:\sonarqube-6.4\temp
2017.06.08 14:16:48 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[es]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-6.4\temp -cp ./lib/common/*;./lib/search/* org.sonar.search.SearchServer C:\sonarqube-6.4\temp\sq-process4446289395140408306properties
2017.06.08 14:16:58 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2017.06.08 14:16:58 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[web]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-6.4\temp -cp ./lib/common/*;./lib/server/*;C:\sonarqube-6.4\lib\jdbc\mysql\mysql-connector-java-5.1.42.jar org.sonar.server.app.WebServer C:\sonarqube-6.4\temp\sq-process8350799980603957914properties
2017.06.08 14:18:41 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
2017.06.08 14:18:41 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[ce]: C:\Program Files\Java\jre1.8.0_121\bin\java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Xmx1024m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=C:\sonarqube-6.4\temp -cp ./lib/common/*;./lib/server/*;./lib/ce/*;C:\sonarqube-6.4\lib\jdbc\mysql\mysql-connector-java-5.1.42.jar org.sonar.ce.app.CeServer C:\sonarqube-6.4\temp\sq-process3864361087787517844properties
2017.06.08 14:18:50 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is up
2017.06.08 14:18:50 INFO  app[][o.s.a.SchedulerImpl] SonarQube is up

**Comment by andreamaruccia** [comment]
Had to uncheck a setting in IIS: AARCache->Server proxy settings ->reverse rewrite host in response headers. Now it seems to work better (I can login with Azure Active Directory) but whenever I load the settings page it fails. I think it must be something related to the reverse proxy because the if I go to the local url it works.
We can close this, obviously not related to the version of sonarqube.

**Comment by hkamel** [comment]
@andreamaruccia thanks for the update, the following post provide some guidance around how to configure IIS and ARR for SonarQube https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/06/04/running-sonarqube-behind-an-iis-reversed-proxy/

**Comment by andreamaruccia** [comment]
Thank you I've gone through it and it works. Last step was to allow longer url's like described in the article. Now everything works like a charm!
