### ISSUE TITLE
AAD authentication does not work with Chrome browser

### ISSUE THREAD

**Issue by berndku** [SonarQubeCommunity/sonar-auth-aad#15]
I successfully setup the AAD extension with SonarQube server and can login with Azure Active Directory credentials on IE, Firefox and Edge, but on Chrome, though the authentication dance with AAD succeeds, SonarQube is showing  the following error: "You´re not authorized to access this page. Pleace contact the administrator". This happens for existing and new users. If it is a new user, the user is not added to the local user list.

**Comment by hkamel** [comment]
@berndku can you share the log also can you try a private tab on chrome?

**Comment by berndku** [comment]
Sent the logs via email. Private tab on chrome leads to same negative result. Looking in the logs, it seems there is an exception in Sonar on the invocation of the aad callback.

**Comment by berndku** [comment]
It works now also in Chrome. The problem seemed to be related to an errorneous reverse proxy configuration in IIS.
