### ISSUE TITLE
getting this error while running sonar with Docker file

### ISSUE THREAD

**Issue by abhaapr24** [SonarQubeCommunity/sonar-auth-aad#16]
[root@9f408ccd75b4 linux-x86-64]# sh sonar.sh console
Running sonar6.4...
wrapper  | --> Wrapper Started as Console
wrapper  | Launching a JVM...
jvm 1    | Wrapper (Version 3.2.3) http://wrapper.tanukisoftware.org
jvm 1    |   Copyright 1999-2006 Tanuki Software, Inc.  All Rights Reserved.
jvm 1    |
jvm 1    | 2017.07.20 11:02:17 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /u01/tt/sonarqube-6.4/temp
jvm 1    | 2017.07.20 11:02:17 INFO  app[][o.s.a.p.JavaProcessLauncherImpl] Launch process[es]: /u01/tt/java/jdk1.8.0_65/jre/bin/java -Djava.awt.headless=true -Xmx1G -Xms256m -Xss256k -Djna.nosys=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -Djava.io.tmpdir=/u01/tt/sonarqube-6.4/temp -cp ./lib/common/*:./lib/search/* org.sonar.search.SearchServer /u01/tt/sonarqube-6.4/temp/sq-process2258841555880924727properties
jvm 1    | 2017.07.20 11:02:28 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
jvm 1    | 2017.07.20 11:02:28 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
wrapper  | <-- Wrapper Stopped
[root@9f408ccd75b4 linux-x86-64]#

**Comment by hkamel** [comment]
@abhaapr24 are you sure this is related to Azure AD plug-in? the log doesn't show any errors related to Azure AD
