### ISSUE TITLE
Plugin artifact link is missing

### ISSUE THREAD

**Issue by egok** [SonarQubeCommunity/sonar-auth-aad#18]
In readme file, under [install azure ad authentication plug in](https://github.com/SonarQubeCommunity/sonar-auth-aad/blob/master/README.md#install-azure-ad-authentication-plug-in), instruction 1 indicates to download and copy the plugin, although there is no link to the plugin artifact **(sonar-auth-aad-plugin-1.0-SNAPSHOT).**

Is one expected to build it [him/her]self or is there a link missing there?

**Comment by hkamel** [comment]
@egok you can download the plug-in from SonarQube Update Center or from this repo under "releases" https://github.com/SonarQubeCommunity/sonar-auth-aad/releases
