### ISSUE TITLE
The redirect URI is localhost?

### ISSUE THREAD

**Issue by marcdonovan** [SonarQubeCommunity/sonar-auth-aad#23]
This would only work if I am using a browser on the Sonar machine. Where does this localhost:9000 URL come from? 

https://login.microsoftonline.com/6416915b-6778-4c36-ba4f-e56ff64a8bb7/oauth2/authorize?client_id=61d6b18c-2bf0-41ad-8713-d518565bf7f8&response_type=code&redirect_uri=**http://localhost:9000**/oauth2/callback/aad&state=s4om23kgqastq9h2s1bsee2llh

I can't find anywhere to configure this. I have a domain name associated with my SonarQube server and it is fronted by Nginx reverse proxy for SSL. So the redirect URI should be https://domain-name.com/oauth2/callback/aad.

**Comment by marcdonovan** [comment]
This is not coming from nginx, since if I hit sonar directly on the box, localhost:9000, I get the same URI with localhost as the redirect_uri returned in the 302 Location header.

**Comment by marcdonovan** [comment]
I fixed this by adding the Server Base URL in the SonarQube configuration. This got me over to microsoft.com, but when I put in my creds and click, the browser goes to http://localhost:9000/sessions/unauthorized

**Comment by marcdonovan** [comment]
That was not in the documentation BTW.

**Comment by marcdonovan** [comment]
It looks like it first forwards login.microsoftonline.com. I enter my email and it says "Taking you to your organization's sign-in page" Then it forwards to http://localhost:9000/sessions/unauthorized. If I curl the URL for the organization's sign-in page, I get a 401 response.

**Comment by marcdonovan** [comment]
I downloaded Fiddler so I could see whats going on. I see a 302 from the SonarQube host GET /oauth2/callback/aad?code=AQABAAIAAABHh4kmS_aKT5XrjzxRAtHzW0LUorUFYOZiyo0ErZGyIYuwrgMhFAlWbJ4vkqF1UBj1mqhjHsanNrAe7CPkHQFmZr7xizTfw_uAvlIcaIYkQAX-6Z3eLtT5cbWGjpwhPfOJJ1eWFHQYYP642xyzeQS97EWaHJIE7AserSBDsuexEpfebHat-wrHpq4yyJR5vnz-FkEWQpztKLgBSwjXOM4Sn-EkZhRz5JhKTCPmDjyhb5aYSVfQSfza3LzSqlB4AkpMa9xJAc1aTCxjhdA6VwMQJYxrZps23rIeeePzLJcAAwkidkh2VnIP767PQRe7ijwqEF5o3QBo9ipkereMV1K_a338yPgG5YCxab_cAX8tXTXskHGB5eNtzUNASKCB3HUYtC64gzLUtKz9Rjpm0NABCl2qKhbfBTjTsPvW2umJ48qL7LiRApzqRsafTBW4_xO3nwAiMN4tGjS6Cr0-lbhB7ozqHTdIXTFC9tAIkM9RYdPhPSJ4INsuh2QMAwrwUINVhdxowQc0QeOsZ3X54MK01Fzld1tfFfg96UmiVdBj5_jL4cqKv1HlEdgx51p-RM-9N0_ethX0yqotny0xzvcQh4I5nyfd_nqto8ZMFUywsfMyNbGKAbCQ6AmBZUGP6MP10UxGAvVatiPc54kRztAwu5JNFD1KQUAoBPPHNq7r57gCguBNZ045BpxLGHsGa3QgAA&state=1f05tu9mljmnlg93reien0rek4&session_state=da9a7099-ec36-46df-b290-

with these headers

HTTP/1.1 302
Server: nginx/1.12.2
Date: Wed, 06 Dec 2017 18:41:10 GMT
Content-Length: 0
Connection: keep-alive
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Set-Cookie: OAUTHSTATE=; Max-Age=0; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Path=/; HttpOnly
Location: http://localhost:9000/sessions/unauthorized

So sonar is sending me to a localhost page, which is not running on my local box. I know I am authenticated since I can browse portal.office.com and I can see my documents.

**Comment by jmprieur** [comment]
Hello @marcdonovan the redirect URL is registered in the Azure portal (https://portal.azure.com) in the section about Azure active directory registered applications: https://portal.azure.com/#blade/Microsoft_AAD_IAM/ApplicationsListBlade

Then find your application and, in the settings for your application, click on **Reply URLs**
HTH

**Comment by strtdusty** [comment]
@jmprieur I don't believe that is correct.  In the Azure portal you register the legal redirect URLs but there can be multiple.  The requesting application actually sends in the requested redirect.

The solution, I believe, is to set the Server base URL under Configuration->General
By default (blank) it uses localhost

**Comment by egok** [comment]
Agree with @strtdusty . 

I can confirm that setting the base URL under Configuration->General in SonarQube would work.

**Comment by Quanjiang** [comment]
@marcdonovan  Do you still have the issue? The localhost was came from soanr setting "sonar.core.serverBaseURL" which one in conf/sonar.properties.  I do have same error from gitlab "The redirect URI included is not valid."  It not work even if you modify the localhost to correct one.

**Comment by Quanjiang** [comment]
@marcdonovan after import ssl cer into gitlab server. we solved this issue. you should make sure the gitlab can access the sonar server (https) and also the "sonar.core.serverBaseURL" was correct setting.

**Comment by sebastiangraf** [comment]
In my case, the configuration of the nginx was not correct, I fixed it according to https://groups.google.com/d/msg/sonarqube/9an4MWxfMwY/bHZihxoeAQAJ an it worked
```
 location /sonar {
      proxy_pass        http://sonarqube:9000/sonar;
      proxy_set_header  X-Forwarded-Proto https;
    }
```

**Comment by rowanibrahem** [comment]
I auth with github , but when I make create project with github he say un auth why
