### ISSUE TITLE
sonar linux with azure AD

### ISSUE THREAD

**Issue by priyakunagu** [SonarQubeCommunity/sonar-auth-aad#28]
HI Team,

we have installed sonarqube 6.0  and sonar DB on 1 azure instance , and we registered our application under azure active directory and configured sonarqube with all the clinet ID, and other stuff mentioned as below 
https://github.com/SonarQubeCommunity/sonar-auth-aad/blob/master/README.md

After this we able to navigate sonar dashbord with azure login - but we are unable to login with our azure account 

some one help us if there is any outh issues related to this azure ad plugins with linux or any other suggestion?

**Comment by hkamel** [comment]
@priyakunagu if this is still an issue, could you please share the logs?

**Comment by hkamel** [comment]
closing as no response provided
