### ISSUE TITLE
MFA support

### ISSUE THREAD

**Issue by an-sush** [SonarQubeCommunity/sonar-auth-aad#37]
Hello,

I see that the plugin doesn't support Multi Factor Authentication. I have my Azure side setup with OpenID (to prompt for MFA after login) and I am not getting prompted for MFA since scope argument isn't passed:

`&scope=openid`

Refer:
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-protocols-openid-connect-code

**Comment by hkamel** [comment]
Thanks @an-sush ... Hello @jmprieur should the authorization URL include the scope=openid to trigger the MFA or there is other way from AAD configuraitons?

**Comment by hkamel** [comment]
Hello @an-sush, I have tried the plug-in against my Azure AD tenant where MFA is enabled and it's working as expected. what exact error are you facing?

**Comment by jmprieur** [comment]
@hkamel if the tenant admin requires MFA for each sign-in, the scope=openid would be enough. Now if the tenant admin requires MFA for other resources that need to be accessed by the plug-in (I don't think that this would be the case for SonarQube / SonarCloud), the scope for this resource should also be provided, in the case of an AAD V1 app (as there is no dynamic consent, contrary to AAD V2)

**Comment by an-sush** [comment]
Hello @hkamel with MFA turned on Azure side, the plugin is just prompting for password and not MFA. It allows login without MFA. Ideally it should challenge for MFA after entering credentials. The pull request #38 is fixing the issue and I have validated it

**Comment by hkamel** [comment]
A new draft release has been published [1.1-RC2](https://github.com/SonarQubeCommunity/sonar-auth-aad/releases/tag/1.1-RC2 ) the [announcement](https://community.sonarsource.com/t/new-release-azure-active-directory-aad-authentication-plug-in-for-sonarqube-1-1-rc2/3117) has been sent to the official SonarSource community to kick the official release.
