### ISSUE TITLE
Group synchronization fails

### ISSUE THREAD

**Issue by Mikkelcv** [SonarQubeCommunity/sonar-auth-aad#41]
I am using the RC1 to try the group synchronization but can see in the log file that it fails on:

ERROR web[AWNuLJbqhnoc6EUDAADj][o.a.a.a.AadIdentityProvider] java.io.IOException: Server returned HTTP response code: 403 for URL:
https://graph.windows.net/<tenantId>/users/<userId>/memberOf?api-version=1.6

(I am able to login)

I have enabled the "Read all groups" under required permissions in the Azure AD for the Web Application.

If I check my sonarcube application via:
https://account.activedirectory.windowsazure.com/r#/applications
Then I can see:
Read all groups
Read all user's basic profiles
Sign you in and read your profile

Any suggestions? or further details I can provide?

**Comment by srvrguy** [comment]
I can confirm this. It looks like graph.windows.net is returning "Authentication_MissingOrMalformed" for the error code. As far as I can determine, it's because the access token doesn't have the grant for the right audience. I'm looking into this further because group sync will be a huge help in making permission management easier.

**Comment by Mikkelcv** [comment]
I did get a little further. In the Azure portal I got my system administrator to press the "Grant Permissions" button under "Required Permissions", and then the plugin could read some group settings however the plugin then failed afterwards and I stopped there. I did not look more into what it failed on.

**Comment by srvrguy** [comment]
Did some more digging, and it's actually a different error. My manual tests missed a few details. Once I double-checked what the code was doing and grabbed the token it was using, I get a different error. Specifically "Authorization_RequestDenied" with the message "Insufficient privileges to complete the operation."

I've made sure that the Group.Read.All permission is selected and the Enterprise Applications section shows the permission is granted via admin consent. Even more interestingly, the token issued shows "Group.Read.All User.Read User.ReadBasic.All" for the scp value and "https://graph.windows.net" for the aud value. In theory, this should allow the group operation it's trying to do. It seems either something's missing or the Microsoft docs are incomplete with the information that's needed to get the data.

**Comment by nickptrvc** [comment]
I was able to get this working on my end. You have to set the following **Delegated Permissions** on the **Windows Azure Active Directory** API. Once you've added those permissions, click "Grant permissions" on the API list blade. 
* Read directory data
* Read all users' basic profiles
* Sign in and read user profile

![sonarqube aad permissions](https://user-images.githubusercontent.com/4001122/44600356-092b2680-a7a7-11e8-9498-27a55217c10e.png)

You also need to create a user group of type **Security** that correlates with group names in SonarQube. Your user then needs to be added to that security group. If my security group in Azure has a group name of **Sonar Admin**, then the group name in SonarQube needs to be exactly the same. This is for the group synchronization. 

Finally, you still need to give user access to the application, so you'll need to add the user to the application's "Users and groups" section. To do this, go to portal.azure.com, All services, Enterprise applications, your application's name (whatever you name your application when registering it), Users and groups, then finally click "Add user" at the top.

Someone should submit a PR to have the instructions updated. I ended up building and deploying this plugin with my own customizations to figure out what was working and what wasn't.

**Comment by Mikkelcv** [comment]
Thank you for figuring this out.
