### ISSUE TITLE
Not able to start SonarQube after adding the Tibco custom plugin in Linux  under sonarqube-7.3\extensions\plugins 

### ISSUE THREAD

**Issue by sujavani** [SonarQubeCommunity/sonar-auth-aad#54]
2018.08.14 04:11:50 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/temp
2018.08.14 04:11:50 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2018.08.14 04:11:50 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/elasticsearch]: /home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/elasticsearch/bin/elasticsearch -Epath.conf=/home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/temp/conf/es
2018.08.14 04:11:50 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2018.08.14 04:11:50 INFO  app[][o.e.p.PluginsService] no modules loaded
2018.08.14 04:11:50 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2018.08.14 04:11:59 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2018.08.14 04:11:59 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3]: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.91-1.b14.el7_2.x86_64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -cp ./lib/common/*:/home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/lib/jdbc/h2/h2-1.3.176.jar org.sonar.server.app.WebServer /home/tibco/Desktop/Sonar/Sonar/sonarqube-7.3/temp/sq-process5724069499550908326properties
2018.08.14 04:12:08 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2018.08.14 04:12:09 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2018.08.14 04:12:09 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
2018.08.14 04:12:09 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped

**Comment by julienlancelot** [comment]
Hi @sujavani, I may be wrong but it seems to me that this issue is not related to the sonar-auth-add-plugin.
So please open a new thread on https://community.sonarsource.org (and to not forget to add more info : list of installed plugin, web logs, etc.) and close this issue.
Thanks

**Comment by sujavani** [comment]
Hi @julienlancelot 
This is the exact error info 
Background initialization failed. Stopping SonarQube
java.lang.IllegalStateException: Fail to load plugin TIBCO BusinessWorks 6 [tibcobw6] I got this error in linux. But the same plugin is working fine in Windows sonarQube
Plugin info: https://github.com/kapilshivarkar/SonarQube-Plugin-for-BusinessWorks6/tree/master/plugin%20jar

Thanks

**Comment by julienlancelot** [comment]
@sujavani As suggested, please close this issue and open a new thread on https://community.sonarsource.org
