### ISSUE TITLE
The ROOT_URL https://login.microsoftonline.com is replaced with my sonar url

### ISSUE THREAD

**Issue by fbouteruche** [SonarQubeCommunity/sonar-auth-aad#6]
Hi,

I have followed your setup guide and when I clicked on Log in with Azure AD, it build a url with my sonar url instead of https://login.microsoftonline.com. If I replace my sonar url in the build url with https://login.microsoftonline.com, I can log in.

Do I missed something ? 

Thanks,
François.

**Comment by hkamel** [comment]
Please disable ARR setting of rewriting host name check this https://github.com/SonarQubeCommunity/sonar-auth-aad/issues/4
