### ISSUE TITLE
blank screen after entering AAD credentials

### ISSUE THREAD

**Issue by Jazaret** [SonarQubeCommunity/sonar-auth-aad#7]
Hello,

I followed the instructions of installation and configuration and got as far as clicking on the "Log in with Azure AD" which takes me to the microsoftonline page where I can enter the microsoft account.  

As soon as I enter valid credentials I get redirected to:

https://sonar.*MyDomain*.com/oauth2/callback/aad?code=AAABAAAA0TWEUN3Y....*andonandon*

which is a blank page.

Any help would be appreciated.

**Comment by hkamel** [comment]
Hello Jazaret, could you please look into sonar.log file and share the error with me? I'll be able to help.

**Comment by Jazaret** [comment]
I checked the logs and see the problem!

> Exception:org.sonar.api.server.authentication.UnauthorizedException: You can't sign up because email 'username@*MyDomain*.com' is already used by an existing user. This means that you probably already registered with another account.

I altered the existing account with the original email address that was registered and it let me in fine. 

BTW this was set using "Login generation strategy": "Default" which is "Unique".

Thank you!

**Comment by hkamel** [comment]
great to hear, will close the issue.
