### ISSUE TITLE
Azure AD authentication + IIS Reverse Proxy = redirect error?

### ISSUE THREAD

**Issue by marcelkieser** [SonarQubeCommunity/sonar-auth-aad#9]
Hi,

can you perhaps drop a hint how to set this up behind an IIS reverse proxy, say on an Azure server?

While I could get Sonarqubes authentication and functionality to work using ARR and Url Rewrite it was not possible for me to get the Azure AD authorization redirect to work.

I have setup a Window server with IIS, ARR and Url Rewrite. I have created a public IP in Azure with a native DNS name (say server.westeurope.cloudapp.azure.com) and enabled https access in the Network Security Group.  And i created a site in IIS and bound it to `https://server.westeurope.cloudapp.azure.com`.

Then I have followed these instructions:
- [Sonarqube: Reverse Proxy](http://docs.sonarqube.org/display/SONAR/Securing+the+Server+Behind+a+Proxy)
- [MSDN: IIS Reverse Proxy](https://blogs.msdn.microsoft.com/friis/2016/08/25/setup-iis-with-url-rewrite-as-a-reverse-proxy-for-real-world-apps/)

That way i added inbound and outbound rules with the reverse proxy template to translate `server.westeurope.cloudapp.azure.com` to `localhost:9000` and back with having ARR's reverse rewrite host enabled in the proxy settings also replacing redirects to the correct server address. With basic Sonarqube authentication the service could be used with the public IP and DNS.

When activating the Azure AD authorization add in and trying to log-in Sonarqube sends a 302 redirect to `login.azure.com` with the configured settings. This works fine on localhost but when using the public IP and the reverse proxy the redirect's host is rewritten to `server.westeurope.cloudapp.azure.com` and fails therefore.

I have tried to disable ARR's reverse rewrite setting as described [here ](http://stackoverflow.com/questions/4243959/iis-reverse-proxy-with-rewrites-cant-handle-a-redirect-from-the-server-we-proxy) but then 

I am unable to find the correct way to resolve this. Any hint would be appreciated.

**Comment by wpschaub** [comment]
Please review [Running SonarQube behind an IIS Reversed Proxy](https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/06/04/running-sonarqube-behind-an-iis-reversed-proxy/).

**Comment by jmprieur** [comment]
Willy-Peter. Did you intend to send this email to almchamps?

Regards
Jean-Marc

**Comment by joehmchan** [comment]
hi marcelkieser,

I encountered the same issue and found this article in msdn. Hopefully it will help.
https://blogs.msdn.microsoft.com/visualstudioalmrangers/2016/06/04/running-sonarqube-behind-an-iis-reversed-proxy/

**Comment by marcelkieser** [comment]
Well, I've tried the MSDN guideline (see above) but still it was not possible to get the Azure AD authentication to work because of the OAuth redirects. As of now I gave up on IIS reverse proxy and switched to NGinx (as described [here](<http://docs.sonarqube.org/display/SONAR/Securing+the+Server+Behind+a+Proxy#SecuringtheServerBehindaProxy-UsingNginx>)) which took about 10 minutes to set up.
